export const businesses = [
  {
    id: "1",
    name: "Cooperative Coffee",
    description: "A cooperatively owned coffee shop.",
    products: [
      { id: "1", name: "Espresso", price: 3 },
      { id: "2", name: "Cappuccino", price: 4 },
      { id: "3", name: "Latte", price: 4 },
      { id: "4", name: "Iced Coffee", price: 3.5 },
      { id: "5", name: "Mocha", price: 4.5 },
      { id: "6", name: "Americano", price: 2.5 },
      { id: "7", name: "Macchiato", price: 3.75 },
      { id: "8", name: "Flat White", price: 4 },
      { id: "9", name: "Cortado", price: 3.5 },
    ],
    reviews: [
      { id: "1", author: "Alice", content: "Great coffee and friendly staff!" },
      { id: "2", author: "Bob", content: "My favorite place to get coffee." },
      { id: "3", author: "Charlie", content: "The espresso is top-notch." },
      { id: "4", author: "Debbie", content: "I love their iced coffee." },
      { id: "5", author: "Eve", content: "The mocha is delicious." },
      { id: "6", author: "Frank", content: "The macchiato is perfect." },
      { id: "7", author: "Grace", content: "The flat white is my go-to." },
      { id: "8", author: "Heidi", content: "The cortado is a hidden gem." },
    ],
  },
  {
    id: "2",
    name: "People's Bookstore",
    description: "A cooperatively owned bookstore.",
    products: [
      { id: "10", name: "1984 by George Orwell", price: 10 },
      { id: "11", name: "To Kill a Mockingbird by Harper Lee", price: 10 },
      { id: "12", name: "The Great Gatsby by F. Scott Fitzgerald", price: 10 },
      { id: "13", name: "Moby-Dick by Herman Melville", price: 15 },
      { id: "14", name: "War and Peace by Leo Tolstoy", price: 20 },
      { id: "15", name: "Ulysses by James Joyce", price: 15 },
      { id: "16", name: "Pride and Prejudice by Jane Austen", price: 10 },
      { id: "17", name: "The Catcher in the Rye by J.D. Salinger", price: 10 },
      { id: "18", name: "The Hobbit by J.R.R. Tolkien", price: 15 },
    ],
    reviews: [
      { id: "9", author: "Ivan", content: "A great selection of books." },
      {
        id: "10",
        author: "Judy",
        content: "I love supporting this local business.",
      },
      {
        id: "11",
        author: "Ken",
        content: "They have all my favorite classics.",
      },
      {
        id: "12",
        author: "Linda",
        content: "The staff is very knowledgeable.",
      },
      { id: "13", author: "Mike", content: "I found some great books here." },
      { id: "14", author: "Nancy", content: "The selection is incredible." },
      {
        id: "15",
        author: "Oscar",
        content: "I always find something new here.",
      },
      { id: "16", author: "Patty", content: "A must-visit for book lovers." },
    ],
  },
  {
    id: "3",
    name: "Green Grocer",
    description: "A cooperatively owned grocery store.",
    products: [
      { id: "19", name: "Apples", price: 1 },
      { id: "20", name: "Bananas", price: 0.5 },
      { id: "21", name: "Carrots", price: 2 },
      { id: "22", name: "Dates", price: 3 },
      { id: "23", name: "Eggs", price: 2.5 },
      { id: "24", name: "Figs", price: 4 },
      { id: "25", name: "Grapes", price: 2 },
      { id: "26", name: "Honey", price: 5 },
      { id: "27", name: "Iceberg Lettuce", price: 1.5 },
    ],
    reviews: [
      {
        id: "17",
        author: "Quincy",
        content: "Fresh produce and friendly staff.",
      },
      {
        id: "18",
        author: "Rita",
        content: "I do all my grocery shopping here.",
      },
      {
        id: "19",
        author: "Steve",
        content: "The best place for organic food.",
      },
      {
        id: "20",
        author: "Tina",
        content: "I love their selection of local products.",
      },
      {
        id: "21",
        author: "Ursula",
        content: "The prices are very reasonable.",
      },
      { id: "22", author: "Victor", content: "A great community resource." },
      {
        id: "23",
        author: "Wendy",
        content: "I appreciate their commitment to sustainability.",
      },
      {
        id: "24",
        author: "Xavier",
        content: "The honey is locally sourced and delicious.",
      },
    ],
  },
  {
    id: "4",
    name: "Harmony Hardware",
    description: "A cooperatively owned hardware store.",
    products: [
      { id: "28", name: "Hammer", price: 10 },
      { id: "29", name: "Screwdriver", price: 8 },
      { id: "30", name: "Wrench", price: 12 },
      { id: "31", name: "Drill", price: 50 },
      { id: "32", name: "Nails", price: 5 },
      { id: "33", name: "Screws", price: 5 },
      { id: "34", name: "Pliers", price: 10 },
      { id: "35", name: "Tape Measure", price: 7 },
      { id: "36", name: "Saw", price: 20 },
    ],
    reviews: [
      { id: "25", author: "Yvonne", content: "Great selection of tools." },
      { id: "26", author: "Zach", content: "Helpful and knowledgeable staff." },
      {
        id: "27",
        author: "Amy",
        content: "My go-to for home improvement projects.",
      },
      {
        id: "28",
        author: "Brian",
        content: "High-quality products at good prices.",
      },
      {
        id: "29",
        author: "Cindy",
        content: "I appreciate their commitment to the community.",
      },
      { id: "30", author: "Dave", content: "The best hardware store in town." },
      { id: "31", author: "Ellen", content: "I always find what I need here." },
      { id: "32", author: "Fred", content: "A great local business." },
    ],
  },
  {
    id: "5",
    name: "Community Clothing",
    description: "A cooperatively owned clothing store.",
    products: [
      { id: "37", name: "T-Shirt", price: 20 },
      { id: "38", name: "Jeans", price: 50 },
      { id: "39", name: "Dress", price: 70 },
      { id: "40", name: "Sweater", price: 40 },
      { id: "41", name: "Jacket", price: 80 },
      { id: "42", name: "Shoes", price: 60 },
      { id: "43", name: "Hat", price: 15 },
      { id: "44", name: "Scarf", price: 20 },
      { id: "45", name: "Gloves", price: 15 },
    ],
    reviews: [
      { id: "33", author: "Gina", content: "Stylish and affordable clothes." },
      { id: "34", author: "Harry", content: "Great customer service." },
      { id: "35", author: "Irene", content: "I love their selection." },
      {
        id: "36",
        author: "Jack",
        content: "High-quality materials and construction.",
      },
      {
        id: "37",
        author: "Karen",
        content: "My favorite place to shop for clothes.",
      },
      {
        id: "38",
        author: "Larry",
        content: "They have something for everyone.",
      },
      {
        id: "39",
        author: "Mona",
        content: "I always find something I love here.",
      },
      {
        id: "40",
        author: "Nick",
        content: "A great place to find unique pieces.",
      },
    ],
  },
  {
    id: "6",
    name: "Bountiful Bakery",
    description: "A cooperatively owned bakery.",
    products: [
      { id: "46", name: "Bread", price: 5 },
      { id: "47", name: "Croissant", price: 3 },
      { id: "48", name: "Muffin", price: 2 },
      { id: "49", name: "Cake", price: 20 },
      { id: "50", name: "Pie", price: 15 },
      { id: "51", name: "Cookie", price: 1 },
      { id: "52", name: "Scone", price: 3 },
      { id: "53", name: "Donut", price: 2 },
      { id: "54", name: "Bagel", price: 2 },
    ],
    reviews: [
      { id: "41", author: "Olivia", content: "Delicious baked goods." },
      { id: "42", author: "Paul", content: "The bread is always fresh." },
      {
        id: "43",
        author: "Quinn",
        content: "The croissants are the best I've ever had.",
      },
      { id: "44", author: "Rachel", content: "I love their muffins." },
      {
        id: "45",
        author: "Sam",
        content: "The cakes are perfect for special occasions.",
      },
      {
        id: "46",
        author: "Tina",
        content: "The pies remind me of my grandmother's.",
      },
      { id: "47", author: "Ursula", content: "The cookies are a treat." },
      {
        id: "48",
        author: "Vince",
        content: "The scones are perfect with a cup of tea.",
      },
    ],
  },
  {
    id: "7",
    name: "Neighborly Nursery",
    description: "A cooperatively owned plant nursery.",
    products: [
      { id: "55", name: "Rose Bush", price: 30 },
      { id: "56", name: "Tomato Plant", price: 10 },
      { id: "57", name: "Maple Tree", price: 50 },
      { id: "58", name: "Basil Plant", price: 5 },
      { id: "59", name: "Orchid", price: 20 },
      { id: "60", name: "Succulent", price: 10 },
      { id: "61", name: "Fern", price: 15 },
      { id: "62", name: "Lavender Plant", price: 12 },
      { id: "63", name: "Mint Plant", price: 5 },
    ],
    reviews: [
      { id: "49", author: "Wendy", content: "A great selection of plants." },
      {
        id: "50",
        author: "Xavier",
        content: "The staff is very knowledgeable.",
      },
      {
        id: "51",
        author: "Yvonne",
        content: "My garden has never looked better.",
      },
      { id: "52", author: "Zach", content: "I love their selection of herbs." },
      { id: "53", author: "Amy", content: "The prices are very reasonable." },
      { id: "54", author: "Brian", content: "A great community resource." },
      {
        id: "55",
        author: "Cindy",
        content: "I appreciate their commitment to sustainability.",
      },
      { id: "56", author: "Dave", content: "The best nursery in town." },
    ],
  },
  {
    id: "8",
    name: "Friendly Furniture",
    description: "A cooperatively owned furniture store.",
    products: [
      { id: "64", name: "Sofa", price: 500 },
      { id: "65", name: "Dining Table", price: 300 },
      { id: "66", name: "Bed Frame", price: 400 },
      { id: "67", name: "Desk", price: 200 },
      { id: "68", name: "Bookshelf", price: 150 },
      { id: "69", name: "Coffee Table", price: 100 },
      { id: "70", name: "Armchair", price: 250 },
      { id: "71", name: "Dresser", price: 350 },
      { id: "72", name: "Nightstand", price: 75 },
    ],
    reviews: [
      {
        id: "57",
        author: "Ellen",
        content: "Stylish and affordable furniture.",
      },
      { id: "58", author: "Frank", content: "Great customer service." },
      { id: "59", author: "Gina", content: "I love their selection." },
      {
        id: "60",
        author: "Harry",
        content: "High-quality materials and construction.",
      },
      {
        id: "61",
        author: "Irene",
        content: "My favorite place to shop for furniture.",
      },
      {
        id: "62",
        author: "Jack",
        content: "They have something for every style.",
      },
      {
        id: "63",
        author: "Karen",
        content: "I always find something I love here.",
      },
      {
        id: "64",
        author: "Larry",
        content: "A great place to find unique pieces.",
      },
    ],
  },

  // Add more businesses as needed
];
