export const businesses = [
  {
    id: "1",
    name: "Cooperative Coffee",
    description: "A cooperatively owned coffee shop.",
    products: [
      { id: "1", name: "Espresso", price: 3 },
      { id: "2", name: "Cappuccino", price: 4 },
      { id: "3", name: "Latte", price: 4 },
      { id: "4", name: "Iced Coffee", price: 3.5 },
      { id: "5", name: "Mocha", price: 4.5 },
      { id: "6", name: "Americano", price: 2.5 },
      { id: "7", name: "Macchiato", price: 3.75 },
      { id: "8", name: "Flat White", price: 4 },
      { id: "9", name: "Cortado", price: 3.5 },
    ],
    reviews: [
      { id: "1", author: "Alice", content: "Great coffee and friendly staff!" },
      { id: "2", author: "Bob", content: "My favorite place to get coffee." },
      { id: "3", author: "Charlie", content: "The espresso is top-notch." },
      { id: "4", author: "Debbie", content: "I love their iced coffee." },
      { id: "5", author: "Eve", content: "The mocha is delicious." },
      { id: "6", author: "Frank", content: "The macchiato is perfect." },
      { id: "7", author: "Grace", content: "The flat white is my go-to." },
      { id: "8", author: "Heidi", content: "The cortado is a hidden gem." },
    ],
  },
  {
    id: "2",
    name: "People's Bookstore",
    description: "A cooperatively owned bookstore.",
    products: [
      { id: "10", name: "1984 by George Orwell", price: 10 },
      { id: "11", name: "To Kill a Mockingbird by Harper Lee", price: 10 },
      { id: "12", name: "The Great Gatsby by F. Scott Fitzgerald", price: 10 },
      { id: "13", name: "Moby-Dick by Herman Melville", price: 15 },
      { id: "14", name: "War and Peace by Leo Tolstoy", price: 20 },
      { id: "15", name: "Ulysses by James Joyce", price: 15 },
      { id: "16", name: "Pride and Prejudice by Jane Austen", price: 10 },
      { id: "17", name: "The Catcher in the Rye by J.D. Salinger", price: 10 },
      { id: "18", name: "The Hobbit by J.R.R. Tolkien", price: 15 },
    ],
    reviews: [
      { id: "9", author: "Ivan", content: "A great selection of books." },
      {
        id: "10",
        author: "Judy",
        content: "I love supporting this local business.",
      },
      {
        id: "11",
        author: "Ken",
        content: "They have all my favorite classics.",
      },
      {
        id: "12",
        author: "Linda",
        content: "The staff is very knowledgeable.",
      },
      { id: "13", author: "Mike", content: "I found some great books here." },
      { id: "14", author: "Nancy", content: "The selection is incredible." },
      {
        id: "15",
        author: "Oscar",
        content: "I always find something new here.",
      },
      { id: "16", author: "Patty", content: "A must-visit for book lovers." },
    ],
  },
  {
    id: "3",
    name: "Green Grocer",
    description: "A cooperatively owned grocery store.",
    products: [
      { id: "19", name: "Apples", price: 1 },
      { id: "20", name: "Bananas", price: 0.5 },
      { id: "21", name: "Carrots", price: 2 },
      { id: "22", name: "Dates", price: 3 },
      { id: "23", name: "Eggs", price: 2.5 },
      { id: "24", name: "Figs", price: 4 },
      { id: "25", name: "Grapes", price: 2 },
      { id: "26", name: "Honey", price: 5 },
      { id: "27", name: "Iceberg Lettuce", price: 1.5 },
    ],
    reviews: [
      {
        id: "17",
        author: "Quincy",
        content: "Fresh produce and friendly staff.",
      },
      {
        id: "18",
        author: "Rita",
        content: "I do all my grocery shopping here.",
      },
      {
        id: "19",
        author: "Steve",
        content: "The best place for organic food.",
      },
      {
        id: "20",
        author: "Tina",
        content: "I love their selection of local products.",
      },
      {
        id: "21",
        author: "Ursula",
        content: "The prices are very reasonable.",
      },
      { id: "22", author: "Victor", content: "A great community resource." },
      {
        id: "23",
        author: "Wendy",
        content: "I appreciate their commitment to sustainability.",
      },
      {
        id: "24",
        author: "Xavier",
        content: "The honey is locally sourced and delicious.",
      },
    ],
  },
  // Add more businesses as needed
];
